export const GEO_DATA: Record<string, Record<string, string[]>> = {
  "O'zbekiston": {
    "Toshkent shahri": ["Bektemir", "Chilonzor", "Mirobod", "Mirzo Ulug'bek", "Olmazor", "Sergeli", "Shayxontohur", "Uchtepa", "Yakkasaroy", "Yangihayot", "Yashnobod", "Yunusobod"],
    "Toshkent viloyati": ["Angren", "Bekobod", "Bostonliq", "Bo'ka", "Chirchiq", "Nurafshon", "Ohangaron", "Oqqo'rg'on", "O'rtachirchiq", "Parkent", "Piskent", "Qibray", "Toshkent tumani", "Yangiyo'l", "Yuqorichirchiq", "Zangiota"],
    "Andijon viloyati": ["Andijon shahri", "Asaka", "Baliqchi", "Bo'ston", "Buloqboshi", "Izbaskan", "Jalaquduq", "Xo'jaobod", "Qo'rg'ontepa", "Marhamat", "Oltinko'l", "Paxtaobod", "Shahrixon", "Ulug'nor"],
    "Farg'ona viloyati": ["Farg'ona shahri", "Oltiariq", "Bag'dod", "Beshariq", "Buvayda", "Dang'ara", "Furqat", "Qo'shtepa", "Quva", "Rishton", "Shirin", "So'x", "Toshloq", "Uchko'prik", "O'zbekiston tumani", "Yozyovon", "Marg'ilon", "Qo'qon", "Quvasoy"],
    "Namangan viloyati": ["Namangan shahri", "Chust", "Kosonsoy", "Mingbuloq", "Namangan tumani", "Norin", "Pop", "To'raqo'rg'on", "Uchqo'rg'on", "Uychi", "Yangi Qo'rg'on"],
    "Samarqand viloyati": ["Samarqand shahri", "Bulung'ur", "Ishtixon", "Jomboy", "Kattaqo'rg'on", "Narpay", "Nurobod", "Oqdaryo", "Pastdarg'om", "Payariq", "Qo'shrabot", "Urgut", "Tayloq", "Toyloq"],
    "Buxoro viloyati": ["Buxoro shahri", "G'ijduvon", "Jondor", "Kogon", "Olot", "Peshku", "Qorakol", "Qorovulbozor", "Romitan", "Shofirkon", "Vobkent"],
    "Qashqadaryo viloyati": ["Qarshi shahri", "Chiroqchi", "Dehqonobod", "G'uzor", "Kasbi", "Kitob", "Koson", "Mirishkor", "Muborak", "Nishon", "Qamashi", "Shahrisabz", "Yakkabog'"],
    "Surxondaryo viloyati": ["Termiz shahri", "Angor", "Bandixon", "Boysun", "Denov", "Jarqo'rg'on", "Muzrabot", "Oltinsoy", "Qiziriq", "Qumqo'rg'on", "Sariosiyo", "Sherobod", "Sho'rchi", "Uzun"],
    "Navoiy viloyati": ["Navoiy shahri", "Karmana", "Konimex", "Navbahor", "Nurota", "Qiziltepa", "Tomdi", "Uchquduq", "Xatirchi", "Zarafshon"],
    "Xorazm viloyati": ["Urganch shahri", "Bog'ot", "Gurlan", "Hazorasp", "Xiva", "Xonqa", "Qo'shko'pir", "Shovot", "Tuproqqal'a", "Yangiariq", "Yangibozor"],
    "Jizzax viloyati": ["Jizzax shahri", "Arnasoy", "Baxmal", "Do'stlik", "Forish", "G'allaorol", "Mirzacho'l", "Paxtakor", "Sharof Rashidov", "Yangiobod", "Zomin", "Zarbdor"],
    "Sirdaryo viloyati": ["Guliston shahri", "Baxt", "Boyovut", "Gurlen", "Mirzaobod", "Oqoltin", "Sardoba", "Sayxunobod", "Sirdaryo", "Xovos", "Yangiyer"],
    "Qoraqalpog'iston": ["Nukus shahri", "Amudaryo", "Beruniy", "Bo'zatov", "Chimboy", "Ellikkala", "Kegeyli", "Mo'ynoq", "Qanliko'l", "Qo'ng'irot", "Qorao'zak", "Shumanay", "Taxtako'pir", "To'rtko'l", "Xo'jayli"],
  },
  "Qozog'iston": {
    "Astana": ["Astana shahri", "Bayqonur"],
    "Almati": ["Almati shahri", "Almati viloyati", "Talgar", "Kaskelen", "Qapsagay"],
    "Shimkent": ["Shimkent shahri", "Turkiston", "Arys", "Kentau"],
    "Qaragandy": ["Qaragandy shahri", "Temirtau", "Balqash", "Zhezqazghan"],
    "Nur-Sulton (Eski)": ["Aqmola", "Ko'kshetau", "Stepnogorsk"],
    "Shyghys Qazaqstan": ["Ust-Kamenogorsk", "Semey", "Ridder"],
    "Qostanay": ["Qostanay shahri", "Rudny", "Lisakovsk"],
    "Atyrau": ["Atyrau shahri", "Maqat"],
    "Mangistau": ["Aktau", "Janaozen"],
    "Pavlodar": ["Pavlodar shahri", "Ekibastuz"],
  },
  "Qirg'iziston": {
    "Bishkek": ["Bishkek shahri", "Lebedinovka", "Tokmok"],
    "O'sh viloyati": ["O'sh shahri", "Qorasuv", "Uzgen", "Nookat", "Aravan"],
    "Chuy viloyati": ["Tokmok", "Kara-Balta", "Kant", "Kemin"],
    "Jalal-Obod": ["Jalal-Obod shahri", "Tash-Ko'mir", "Mayluu-Suu", "Suzak"],
    "Issiq-Ko'l": ["Karakol", "Balykchy", "Cholpon-Ata"],
    "Naryn": ["Naryn shahri", "At-Bashy"],
    "Batken": ["Batken", "Suluktu", "Isfana", "Kyzyl-Kiya"],
    "Talas": ["Talas shahri", "Manas"],
  },
  "Tojikiston": {
    "Dushanbe": ["Dushanbe shahri", "Vahdat", "Tursunzoda"],
    "So'g'd viloyati": ["Xo'jand", "Istaravshan", "Konibodom", "Isfara", "Panjikent", "Taboshar"],
    "Xatlon viloyati": ["Bokhtar", "Ko'lob", "Qurghonteppa", "Danghara", "Vose"],
    "GBAO": ["Xorug'", "Murghob", "Ishkoshim"],
    "Respublika bo'ysunmagan hududlar": ["Roghun", "Nurek", "Tursunzoda"],
  },
  "Turkmaniston": {
    "Ashgabat": ["Ashgabat shahri"],
    "Ahal viloyati": ["Anau", "Baharly", "Tejen"],
    "Balkan viloyati": ["Balkanabat", "Turkmenbashi", "Serdar"],
    "Dashoguz viloyati": ["Dashoguz shahri", "Ko'neurgench"],
    "Lebap viloyati": ["Turkmenabat", "Gaurdak", "Farab"],
    "Mary viloyati": ["Mary shahri", "Bayramaly", "Yoloten"],
  },
  "Rossiya": {
    "Moskva": ["Moskva shahri", "Podolsk", "Mytishchi", "Balashikha", "Khimki", "Korolev"],
    "Sankt-Peterburg": ["Sankt-Peterburg shahri", "Pushkin", "Pavlovsk", "Kolpino"],
    "Novosibirsk": ["Novosibirsk shahri", "Berdsk", "Ob'"],
    "Yekaterinburg": ["Yekaterinburg shahri", "Pervouralsk", "Nizhny Tagil"],
    "Qozon": ["Qozon shahri", "Zelenodolsk", "Naberezhnye Chelny"],
    "Krasnodar": ["Krasnodar shahri", "Sochi", "Novorossiysk", "Anapa"],
    "Tumen": ["Tumen shahri", "Tobolsk", "Ishim"],
    "Omsk": ["Omsk shahri"],
    "Samara": ["Samara shahri", "Tolyatti"],
    "Rostov-na-Donu": ["Rostov shahri", "Taganrog", "Shakhty"],
  },
  "Turkiya": {
    "Istanbul": ["Istanbul (Avrupa)", "Istanbul (Anadolu)", "Besiktas", "Kadikoy", "Uskudar"],
    "Ankara": ["Ankara shahri", "Sincan", "Kecioren", "Mamak"],
    "Izmir": ["Izmir shahri", "Karsiyaka", "Bornova", "Konak"],
    "Antalya": ["Antalya shahri", "Alanya", "Manavgat", "Kemer", "Side"],
    "Bursa": ["Bursa shahri", "Osmangazi", "Nilufer"],
    "Adana": ["Adana shahri", "Mersin", "Tarsus"],
    "Gaziantep": ["Gaziantep shahri", "Islahiye"],
    "Konya": ["Konya shahri", "Eregli"],
    "Mersin": ["Mersin shahri", "Tarsus", "Silifke"],
    "Trabzon": ["Trabzon shahri", "Rize"],
  },
  "Ukraina": {
    "Kiyev": ["Kiyev shahri", "Boryspil", "Brovary", "Bila Tserkva"],
    "Xarkiv": ["Xarkiv shahri", "Izium"],
    "Dnipro": ["Dnipro shahri", "Kryvyi Rih"],
    "Odessa": ["Odessa shahri", "Izmail", "Bilhorod-Dnistrovskyi"],
    "Lviv": ["Lviv shahri", "Drohobych", "Boryslav"],
    "Zaporizhzhia": ["Zaporizhzhia shahri", "Enerhodar"],
  },
  "Ozarbayjon": {
    "Boku": ["Boku shahri", "Sumqayit", "Ganja", "Mingachevir"],
    "Absheron": ["Sumqayit", "Khirdalan", "Neftchala"],
    "Ganja-Qazax": ["Ganja shahri", "Qazax", "Samux"],
    "Lenkoran": ["Lenkoran shahri", "Astara", "Masalli"],
    "Sheki-Zaqatala": ["Sheki shahri", "Zaqatala", "Balakan"],
  },
  "Gruziya": {
    "Tbilisi": ["Tbilisi shahri", "Rustavi"],
    "Adjara": ["Batumi", "Kobuleti", "Khelvachauri"],
    "Imereti": ["Kutaisi", "Zestafoni"],
    "Samegrelo": ["Zugdidi", "Poti", "Senaki"],
    "Kvemo Kartli": ["Rustavi", "Gardabani", "Bolnisi"],
  },
  "Armaniston": {
    "Yerevan": ["Yerevan shahri", "Abovyan"],
    "Lorri": ["Vanadzor", "Alaverdi"],
    "Shirak": ["Gyumri shahri", "Artik"],
    "Aragatsotn": ["Aparan", "Ashtarak"],
  },
  "Germaniya": {
    "Berlin": ["Berlin shahri", "Spandau", "Mitte", "Kreuzberg"],
    "Bavariya": ["Myunxen", "Nyurnberg", "Augsburg", "Regensburg"],
    "Gamburg": ["Gamburg shahri", "Altona", "Eppendorf"],
    "Saksiya": ["Drezden", "Leypsig", "Kemnis"],
    "Nort Rayn-Vestfaliya": ["Kyoln", "Dusseldorf", "Dortmund", "Essen"],
  },
  "Fransiya": {
    "Ile-de-Frans": ["Parij shahri", "Versay", "Montreyil"],
    "Provanss": ["Marsel", "Nissa", "Aix-en-Provans"],
    "Oksitaniya": ["Tuluza", "Monpelye"],
    "Nov-Akiten": ["Bordo", "Limos"],
    "O-de-Frans": ["Lil", "Amyen"],
  },
  "Italiya": {
    "Latsio": ["Rim shahri", "Latina", "Frosinone"],
    "Lombardiya": ["Milan shahri", "Bergamo", "Breschia"],
    "Kampaniya": ["Neapol shahri", "Salerno", "Kaserta"],
    "Sitsiliya": ["Palermo", "Kataniya", "Messina"],
    "Veneto": ["Venetsiya", "Verona", "Padua"],
  },
  "BAA": {
    "Dubay": ["Dubay shahri", "Deira", "Bur Dubai", "Jumeyra", "Marina"],
    "Abu-Dabi": ["Abu-Dabi shahri", "Al Ain", "Mussafah"],
    "Sharjah": ["Sharjah shahri"],
    "Ajman": ["Ajman shahri"],
    "Ra's al-Xayma": ["Ra's al-Xayma shahri"],
  },
  "Saudiya Arabistoni": {
    "Ar-Riyod": ["Riyod shahri", "Diriyah"],
    "Makka": ["Makka shahri", "Jidda", "Toyif"],
    "Madina": ["Madina shahri", "Yanbu"],
    "Sharqiy viloyat": ["Dammam", "Xabar", "Dahran"],
  },
  "Xitoy": {
    "Pekin": ["Pekin shahri"],
    "Shanxay": ["Shanxay shahri", "Pudon"],
    "Guangdun": ["Guangjou", "Shenzhen", "Dongguan"],
    "Chejyan": ["Xanchzhou", "Ninbo", "Venjou"],
    "Sinin'syan": ["Urumchi", "Qoshqar", "Ghulja"],
  },
  "Janubiy Koreya": {
    "Seul": ["Seul shahri", "Gangnam", "Incheon"],
    "Busan": ["Busan shahri", "Gijang"],
    "Daegu": ["Daegu shahri"],
    "Gyeonggi-do": ["Suwon", "Seongnam", "Goyang"],
  },
  "Yaponiya": {
    "Tokio": ["Tokio shahri", "Shinjuku", "Shibuya", "Akihabara"],
    "Osaka": ["Osaka shahri", "Kyoto", "Kobe"],
    "Aichi": ["Nagoya shahri"],
    "Fukuoka": ["Fukuoka shahri"],
  },
};
